// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goods_data.proto

package goods

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Toppings struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               int64    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Toppings) Reset()         { *m = Toppings{} }
func (m *Toppings) String() string { return proto.CompactTextString(m) }
func (*Toppings) ProtoMessage()    {}
func (*Toppings) Descriptor() ([]byte, []int) {
	return fileDescriptor_638e4dc6c83c8cc0, []int{0}
}

func (m *Toppings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Toppings.Unmarshal(m, b)
}
func (m *Toppings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Toppings.Marshal(b, m, deterministic)
}
func (m *Toppings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Toppings.Merge(m, src)
}
func (m *Toppings) XXX_Size() int {
	return xxx_messageInfo_Toppings.Size(m)
}
func (m *Toppings) XXX_DiscardUnknown() {
	xxx_messageInfo_Toppings.DiscardUnknown(m)
}

var xxx_messageInfo_Toppings proto.InternalMessageInfo

func (m *Toppings) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Toppings) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Toppings) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Toppings) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateGoodsSPURequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Kind                 int32    `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ImgURL               string   `protobuf:"bytes,4,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ToppingsID           []int64  `protobuf:"varint,6,rep,packed,name=toppingsID,proto3" json:"toppingsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGoodsSPURequest) Reset()         { *m = CreateGoodsSPURequest{} }
func (m *CreateGoodsSPURequest) String() string { return proto.CompactTextString(m) }
func (*CreateGoodsSPURequest) ProtoMessage()    {}
func (*CreateGoodsSPURequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_638e4dc6c83c8cc0, []int{1}
}

func (m *CreateGoodsSPURequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGoodsSPURequest.Unmarshal(m, b)
}
func (m *CreateGoodsSPURequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGoodsSPURequest.Marshal(b, m, deterministic)
}
func (m *CreateGoodsSPURequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGoodsSPURequest.Merge(m, src)
}
func (m *CreateGoodsSPURequest) XXX_Size() int {
	return xxx_messageInfo_CreateGoodsSPURequest.Size(m)
}
func (m *CreateGoodsSPURequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGoodsSPURequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGoodsSPURequest proto.InternalMessageInfo

func (m *CreateGoodsSPURequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGoodsSPURequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateGoodsSPURequest) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *CreateGoodsSPURequest) GetImgURL() string {
	if m != nil {
		return m.ImgURL
	}
	return ""
}

func (m *CreateGoodsSPURequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateGoodsSPURequest) GetToppingsID() []int64 {
	if m != nil {
		return m.ToppingsID
	}
	return nil
}

type CreateGoodsSPUResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGoodsSPUResponse) Reset()         { *m = CreateGoodsSPUResponse{} }
func (m *CreateGoodsSPUResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGoodsSPUResponse) ProtoMessage()    {}
func (*CreateGoodsSPUResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_638e4dc6c83c8cc0, []int{2}
}

func (m *CreateGoodsSPUResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGoodsSPUResponse.Unmarshal(m, b)
}
func (m *CreateGoodsSPUResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGoodsSPUResponse.Marshal(b, m, deterministic)
}
func (m *CreateGoodsSPUResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGoodsSPUResponse.Merge(m, src)
}
func (m *CreateGoodsSPUResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGoodsSPUResponse.Size(m)
}
func (m *CreateGoodsSPUResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGoodsSPUResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGoodsSPUResponse proto.InternalMessageInfo

type CreateGoodsSKURequest struct {
	SpuID                int64    `protobuf:"varint,1,opt,name=spuID,proto3" json:"spuID,omitempty"`
	CurrentPrice         float64  `protobuf:"fixed64,2,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	OriginalPrice        float64  `protobuf:"fixed64,3,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGoodsSKURequest) Reset()         { *m = CreateGoodsSKURequest{} }
func (m *CreateGoodsSKURequest) String() string { return proto.CompactTextString(m) }
func (*CreateGoodsSKURequest) ProtoMessage()    {}
func (*CreateGoodsSKURequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_638e4dc6c83c8cc0, []int{3}
}

func (m *CreateGoodsSKURequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGoodsSKURequest.Unmarshal(m, b)
}
func (m *CreateGoodsSKURequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGoodsSKURequest.Marshal(b, m, deterministic)
}
func (m *CreateGoodsSKURequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGoodsSKURequest.Merge(m, src)
}
func (m *CreateGoodsSKURequest) XXX_Size() int {
	return xxx_messageInfo_CreateGoodsSKURequest.Size(m)
}
func (m *CreateGoodsSKURequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGoodsSKURequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGoodsSKURequest proto.InternalMessageInfo

func (m *CreateGoodsSKURequest) GetSpuID() int64 {
	if m != nil {
		return m.SpuID
	}
	return 0
}

func (m *CreateGoodsSKURequest) GetCurrentPrice() float64 {
	if m != nil {
		return m.CurrentPrice
	}
	return 0
}

func (m *CreateGoodsSKURequest) GetOriginalPrice() float64 {
	if m != nil {
		return m.OriginalPrice
	}
	return 0
}

func (m *CreateGoodsSKURequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateGoodsSKUResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGoodsSKUResponse) Reset()         { *m = CreateGoodsSKUResponse{} }
func (m *CreateGoodsSKUResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGoodsSKUResponse) ProtoMessage()    {}
func (*CreateGoodsSKUResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_638e4dc6c83c8cc0, []int{4}
}

func (m *CreateGoodsSKUResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGoodsSKUResponse.Unmarshal(m, b)
}
func (m *CreateGoodsSKUResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGoodsSKUResponse.Marshal(b, m, deterministic)
}
func (m *CreateGoodsSKUResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGoodsSKUResponse.Merge(m, src)
}
func (m *CreateGoodsSKUResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGoodsSKUResponse.Size(m)
}
func (m *CreateGoodsSKUResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGoodsSKUResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGoodsSKUResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Toppings)(nil), "goods.toppings")
	proto.RegisterType((*CreateGoodsSPURequest)(nil), "goods.createGoodsSPURequest")
	proto.RegisterType((*CreateGoodsSPUResponse)(nil), "goods.createGoodsSPUResponse")
	proto.RegisterType((*CreateGoodsSKURequest)(nil), "goods.createGoodsSKURequest")
	proto.RegisterType((*CreateGoodsSKUResponse)(nil), "goods.createGoodsSKUResponse")
}

func init() { proto.RegisterFile("goods_data.proto", fileDescriptor_638e4dc6c83c8cc0) }

var fileDescriptor_638e4dc6c83c8cc0 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xd1, 0x4a, 0xeb, 0x40,
	0x10, 0x65, 0x93, 0xa6, 0xdc, 0xce, 0xd5, 0x22, 0x4b, 0x2d, 0x41, 0x54, 0x42, 0xf0, 0x21, 0x4f,
	0x7d, 0xd0, 0x5f, 0x28, 0x48, 0x89, 0x42, 0x59, 0xe9, 0x9b, 0x20, 0x31, 0x59, 0xc2, 0xa2, 0xdd,
	0x5d, 0x77, 0x37, 0x2f, 0xfe, 0x82, 0xdf, 0xe1, 0x07, 0xf8, 0x87, 0x92, 0x49, 0x5a, 0x93, 0x50,
	0x7d, 0x9b, 0x39, 0x3b, 0x39, 0x73, 0xce, 0x99, 0xc0, 0x49, 0xa9, 0x54, 0x61, 0x9f, 0x8a, 0xcc,
	0x65, 0x0b, 0x6d, 0x94, 0x53, 0x34, 0x40, 0x24, 0x7e, 0x84, 0x7f, 0x4e, 0x69, 0x2d, 0x64, 0x69,
	0xe9, 0x14, 0x3c, 0x51, 0x84, 0x24, 0x22, 0x89, 0xcf, 0x3c, 0x51, 0x50, 0x0a, 0x23, 0x99, 0x6d,
	0x79, 0xe8, 0x45, 0x24, 0x99, 0x30, 0xac, 0xe9, 0x1c, 0xc6, 0xd6, 0x65, 0xae, 0xb2, 0xa1, 0x8f,
	0x73, 0x6d, 0x47, 0x67, 0x10, 0x68, 0x23, 0x72, 0x1e, 0x8e, 0x22, 0x92, 0x10, 0xd6, 0x34, 0xf1,
	0x17, 0x81, 0xd3, 0xdc, 0xf0, 0xcc, 0xf1, 0xdb, 0x7a, 0xdb, 0xc3, 0x7a, 0xc3, 0xf8, 0x5b, 0xc5,
	0xad, 0xdb, 0x73, 0x93, 0x0e, 0x77, 0x04, 0xff, 0x0b, 0x6e, 0x73, 0x23, 0xb4, 0x13, 0x4a, 0xb6,
	0x6b, 0xbb, 0x50, 0xfd, 0xd5, 0x8b, 0x90, 0x05, 0xee, 0x0e, 0x18, 0xd6, 0xb5, 0x22, 0xb1, 0x2d,
	0x37, 0xec, 0x0e, 0x57, 0x4f, 0x58, 0xdb, 0x75, 0x94, 0x06, 0x38, 0xbd, 0x53, 0x7a, 0x09, 0xb0,
	0x73, 0xbc, 0x5a, 0x86, 0xe3, 0xc8, 0x4f, 0x7c, 0xd6, 0x41, 0xe2, 0x10, 0xe6, 0x43, 0xc9, 0x56,
	0x2b, 0x69, 0x79, 0xfc, 0x31, 0x70, 0x93, 0xee, 0xdd, 0xcc, 0x20, 0xb0, 0xba, 0x5a, 0x2d, 0xdb,
	0xf0, 0x9a, 0x86, 0xc6, 0x70, 0x94, 0x57, 0xc6, 0x70, 0xe9, 0xd6, 0x18, 0x8d, 0x87, 0xd1, 0xf4,
	0x30, 0x7a, 0x05, 0xc7, 0xca, 0x88, 0x52, 0xc8, 0xec, 0xb5, 0x19, 0xf2, 0x71, 0xa8, 0x0f, 0xd6,
	0xbe, 0xad, 0x78, 0x6f, 0xc2, 0x0d, 0x18, 0xd6, 0x43, 0x9d, 0xe9, 0x5e, 0xe7, 0xf5, 0x27, 0x81,
	0xe6, 0xba, 0xf4, 0x1e, 0xa6, 0x7d, 0x2f, 0xf4, 0x7c, 0x81, 0x2f, 0x8b, 0x83, 0x57, 0x39, 0xbb,
	0xf8, 0xe5, 0xb5, 0x21, 0x1e, 0xd2, 0xa5, 0x87, 0xe9, 0xd2, 0x3f, 0xe9, 0x7e, 0x74, 0x3e, 0x8f,
	0xf1, 0x4f, 0xbc, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x95, 0x34, 0xef, 0x8b, 0x9d, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodsClient is the client API for Goods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodsClient interface {
	CreateGoodsSPU(ctx context.Context, in *CreateGoodsSPURequest, opts ...grpc.CallOption) (*CreateGoodsSPUResponse, error)
	CreateGoodsSKU(ctx context.Context, in *CreateGoodsSKURequest, opts ...grpc.CallOption) (*CreateGoodsSKUResponse, error)
}

type goodsClient struct {
	cc *grpc.ClientConn
}

func NewGoodsClient(cc *grpc.ClientConn) GoodsClient {
	return &goodsClient{cc}
}

func (c *goodsClient) CreateGoodsSPU(ctx context.Context, in *CreateGoodsSPURequest, opts ...grpc.CallOption) (*CreateGoodsSPUResponse, error) {
	out := new(CreateGoodsSPUResponse)
	err := c.cc.Invoke(ctx, "/goods.goods/createGoodsSPU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) CreateGoodsSKU(ctx context.Context, in *CreateGoodsSKURequest, opts ...grpc.CallOption) (*CreateGoodsSKUResponse, error) {
	out := new(CreateGoodsSKUResponse)
	err := c.cc.Invoke(ctx, "/goods.goods/createGoodsSKU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServer is the server API for Goods service.
type GoodsServer interface {
	CreateGoodsSPU(context.Context, *CreateGoodsSPURequest) (*CreateGoodsSPUResponse, error)
	CreateGoodsSKU(context.Context, *CreateGoodsSKURequest) (*CreateGoodsSKUResponse, error)
}

// UnimplementedGoodsServer can be embedded to have forward compatible implementations.
type UnimplementedGoodsServer struct {
}

func (*UnimplementedGoodsServer) CreateGoodsSPU(ctx context.Context, req *CreateGoodsSPURequest) (*CreateGoodsSPUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoodsSPU not implemented")
}
func (*UnimplementedGoodsServer) CreateGoodsSKU(ctx context.Context, req *CreateGoodsSKURequest) (*CreateGoodsSKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoodsSKU not implemented")
}

func RegisterGoodsServer(s *grpc.Server, srv GoodsServer) {
	s.RegisterService(&_Goods_serviceDesc, srv)
}

func _Goods_CreateGoodsSPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodsSPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateGoodsSPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.goods/CreateGoodsSPU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateGoodsSPU(ctx, req.(*CreateGoodsSPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_CreateGoodsSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodsSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateGoodsSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.goods/CreateGoodsSKU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateGoodsSKU(ctx, req.(*CreateGoodsSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Goods_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goods.goods",
	HandlerType: (*GoodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createGoodsSPU",
			Handler:    _Goods_CreateGoodsSPU_Handler,
		},
		{
			MethodName: "createGoodsSKU",
			Handler:    _Goods_CreateGoodsSKU_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods_data.proto",
}
