// Code generated by goctl. DO NOT EDIT.
package types

type UpdateWechatSessionKeyRequest struct {
	JsCode string `form:"jscode"`
}

type UpdateWechatSessionKeyResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
