// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	member "cake-mall/api/internal/handler/member"
	order "cake-mall/api/internal/handler/order"
	"cake-mall/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/member/updateWechatSessionKey",
				Handler: member.UpdateWechatSessionKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/member/login",
				Handler: member.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/member/createUser",
				Handler: member.CreateUserHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/createOrder",
				Handler: order.CreateOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
