// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cake-mall/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/members/updateWechatSessionKey",
				Handler: updateWechatSessionKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/members/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)
}
