// Code generated by goctl. DO NOT EDIT!
// Source: goods_data.proto

package server

import (
	"context"

	"cake-mall/rpc/goods-data/goods"
	"cake-mall/rpc/goods-data/internal/logic"
	"cake-mall/rpc/goods-data/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) CreateGoodsSPU(ctx context.Context, in *goods.CreateGoodsSPURequest) (*goods.CreateGoodsSPUResponse, error) {
	l := logic.NewCreateGoodsSPULogic(ctx, s.svcCtx)
	return l.CreateGoodsSPU(in)
}

func (s *GoodsServer) CreateGoodsSKU(ctx context.Context, in *goods.CreateGoodsSKURequest) (*goods.CreateGoodsSKUResponse, error) {
	l := logic.NewCreateGoodsSKULogic(ctx, s.svcCtx)
	return l.CreateGoodsSKU(in)
}
