// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member_data.proto

package member

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateSessionKeyByUnionIdRequest struct {
	UnionId              string   `protobuf:"bytes,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSessionKeyByUnionIdRequest) Reset()         { *m = UpdateSessionKeyByUnionIdRequest{} }
func (m *UpdateSessionKeyByUnionIdRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSessionKeyByUnionIdRequest) ProtoMessage()    {}
func (*UpdateSessionKeyByUnionIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4010a41aeb367e84, []int{0}
}

func (m *UpdateSessionKeyByUnionIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Unmarshal(m, b)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Merge(m, src)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Size(m)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSessionKeyByUnionIdRequest proto.InternalMessageInfo

func (m *UpdateSessionKeyByUnionIdRequest) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *UpdateSessionKeyByUnionIdRequest) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

type UpdateSessionKeyByUnionIdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSessionKeyByUnionIdResponse) Reset()         { *m = UpdateSessionKeyByUnionIdResponse{} }
func (m *UpdateSessionKeyByUnionIdResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSessionKeyByUnionIdResponse) ProtoMessage()    {}
func (*UpdateSessionKeyByUnionIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4010a41aeb367e84, []int{1}
}

func (m *UpdateSessionKeyByUnionIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Unmarshal(m, b)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Merge(m, src)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Size(m)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSessionKeyByUnionIdResponse proto.InternalMessageInfo

type VerifyUserNumberWithPwdRequest struct {
	UserNumber           int64    `protobuf:"varint,1,opt,name=userNumber,proto3" json:"userNumber,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserNumberWithPwdRequest) Reset()         { *m = VerifyUserNumberWithPwdRequest{} }
func (m *VerifyUserNumberWithPwdRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserNumberWithPwdRequest) ProtoMessage()    {}
func (*VerifyUserNumberWithPwdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4010a41aeb367e84, []int{2}
}

func (m *VerifyUserNumberWithPwdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserNumberWithPwdRequest.Unmarshal(m, b)
}
func (m *VerifyUserNumberWithPwdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserNumberWithPwdRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserNumberWithPwdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserNumberWithPwdRequest.Merge(m, src)
}
func (m *VerifyUserNumberWithPwdRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserNumberWithPwdRequest.Size(m)
}
func (m *VerifyUserNumberWithPwdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserNumberWithPwdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserNumberWithPwdRequest proto.InternalMessageInfo

func (m *VerifyUserNumberWithPwdRequest) GetUserNumber() int64 {
	if m != nil {
		return m.UserNumber
	}
	return 0
}

func (m *VerifyUserNumberWithPwdRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyUserNumberWithPwdResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserNumberWithPwdResponse) Reset()         { *m = VerifyUserNumberWithPwdResponse{} }
func (m *VerifyUserNumberWithPwdResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserNumberWithPwdResponse) ProtoMessage()    {}
func (*VerifyUserNumberWithPwdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4010a41aeb367e84, []int{3}
}

func (m *VerifyUserNumberWithPwdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserNumberWithPwdResponse.Unmarshal(m, b)
}
func (m *VerifyUserNumberWithPwdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserNumberWithPwdResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserNumberWithPwdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserNumberWithPwdResponse.Merge(m, src)
}
func (m *VerifyUserNumberWithPwdResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserNumberWithPwdResponse.Size(m)
}
func (m *VerifyUserNumberWithPwdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserNumberWithPwdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserNumberWithPwdResponse proto.InternalMessageInfo

func (m *VerifyUserNumberWithPwdResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*UpdateSessionKeyByUnionIdRequest)(nil), "member.updateSessionKeyByUnionIdRequest")
	proto.RegisterType((*UpdateSessionKeyByUnionIdResponse)(nil), "member.updateSessionKeyByUnionIdResponse")
	proto.RegisterType((*VerifyUserNumberWithPwdRequest)(nil), "member.verifyUserNumberWithPwdRequest")
	proto.RegisterType((*VerifyUserNumberWithPwdResponse)(nil), "member.verifyUserNumberWithPwdResponse")
}

func init() { proto.RegisterFile("member_data.proto", fileDescriptor_4010a41aeb367e84) }

var fileDescriptor_4010a41aeb367e84 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x62, 0xd5, 0xb9, 0x39, 0x07, 0xad, 0x3d, 0xd4, 0xb5, 0x82, 0xae, 0x97, 0x1e,
	0xf4, 0xe4, 0xd5, 0x9b, 0x08, 0x22, 0x95, 0xc5, 0xcb, 0x82, 0x64, 0xe9, 0x88, 0x15, 0xb6, 0x89,
	0x99, 0xc4, 0xa5, 0x7f, 0xd8, 0xdf, 0x21, 0x26, 0xd9, 0xb0, 0x97, 0x6e, 0x3d, 0xce, 0x9b, 0x97,
	0x97, 0x2f, 0x8f, 0xc0, 0xd1, 0x92, 0x96, 0x0b, 0xd2, 0x6f, 0x8d, 0x30, 0xa2, 0x52, 0x5a, 0x1a,
	0x89, 0xa9, 0x97, 0xca, 0x39, 0x4c, 0xac, 0x6a, 0x84, 0xa1, 0x17, 0x62, 0x6e, 0x65, 0xf7, 0x48,
	0xfd, 0x7d, 0x3f, 0xeb, 0x5a, 0xd9, 0x3d, 0x34, 0x35, 0x7d, 0x59, 0x62, 0x83, 0x19, 0xec, 0x5b,
	0xaf, 0x64, 0xc9, 0x24, 0x99, 0x1e, 0xd6, 0xeb, 0x11, 0x0b, 0x00, 0x8e, 0xe7, 0xb2, 0x1d, 0xb7,
	0xdc, 0x50, 0xca, 0x0b, 0x38, 0xdf, 0x92, 0xce, 0x4a, 0x76, 0x4c, 0xe5, 0x1c, 0x8a, 0x6f, 0xd2,
	0xed, 0x7b, 0x3f, 0x63, 0xd2, 0x4f, 0xf6, 0x0f, 0xeb, 0xb5, 0x35, 0x1f, 0xcf, 0xab, 0x08, 0x50,
	0x00, 0xd8, 0xb8, 0x73, 0x0c, 0xbb, 0xf5, 0x86, 0x82, 0x39, 0x1c, 0x28, 0xc1, 0xbc, 0x92, 0xba,
	0x09, 0x10, 0x71, 0x2e, 0xef, 0xe0, 0x6c, 0x30, 0xdd, 0x03, 0xe0, 0x31, 0xa4, 0x6c, 0x84, 0xb1,
	0xec, 0xa2, 0xf7, 0xea, 0x30, 0xdd, 0xfc, 0x24, 0x10, 0x6a, 0x42, 0x05, 0xa7, 0x83, 0x0f, 0xc1,
	0x69, 0xe5, 0x5d, 0xd5, 0x58, 0x93, 0xf9, 0xf5, 0x3f, 0x9c, 0x01, 0xea, 0x13, 0x4e, 0x06, 0xb8,
	0xf1, 0x72, 0x9d, 0xb2, 0xbd, 0xb6, 0xfc, 0x6a, 0xd4, 0xe7, 0xef, 0x5a, 0xa4, 0xee, 0x4f, 0xdc,
	0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x08, 0x90, 0x53, 0xfd, 0x28, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberClient is the client API for Member service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberClient interface {
	UpdateSessionKeyByUnionId(ctx context.Context, in *UpdateSessionKeyByUnionIdRequest, opts ...grpc.CallOption) (*UpdateSessionKeyByUnionIdResponse, error)
	VerifyUserNumberWithPwd(ctx context.Context, in *VerifyUserNumberWithPwdRequest, opts ...grpc.CallOption) (*VerifyUserNumberWithPwdResponse, error)
}

type memberClient struct {
	cc *grpc.ClientConn
}

func NewMemberClient(cc *grpc.ClientConn) MemberClient {
	return &memberClient{cc}
}

func (c *memberClient) UpdateSessionKeyByUnionId(ctx context.Context, in *UpdateSessionKeyByUnionIdRequest, opts ...grpc.CallOption) (*UpdateSessionKeyByUnionIdResponse, error) {
	out := new(UpdateSessionKeyByUnionIdResponse)
	err := c.cc.Invoke(ctx, "/member.member/updateSessionKeyByUnionId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) VerifyUserNumberWithPwd(ctx context.Context, in *VerifyUserNumberWithPwdRequest, opts ...grpc.CallOption) (*VerifyUserNumberWithPwdResponse, error) {
	out := new(VerifyUserNumberWithPwdResponse)
	err := c.cc.Invoke(ctx, "/member.member/verifyUserNumberWithPwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServer is the server API for Member service.
type MemberServer interface {
	UpdateSessionKeyByUnionId(context.Context, *UpdateSessionKeyByUnionIdRequest) (*UpdateSessionKeyByUnionIdResponse, error)
	VerifyUserNumberWithPwd(context.Context, *VerifyUserNumberWithPwdRequest) (*VerifyUserNumberWithPwdResponse, error)
}

// UnimplementedMemberServer can be embedded to have forward compatible implementations.
type UnimplementedMemberServer struct {
}

func (*UnimplementedMemberServer) UpdateSessionKeyByUnionId(ctx context.Context, req *UpdateSessionKeyByUnionIdRequest) (*UpdateSessionKeyByUnionIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSessionKeyByUnionId not implemented")
}
func (*UnimplementedMemberServer) VerifyUserNumberWithPwd(ctx context.Context, req *VerifyUserNumberWithPwdRequest) (*VerifyUserNumberWithPwdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUserNumberWithPwd not implemented")
}

func RegisterMemberServer(s *grpc.Server, srv MemberServer) {
	s.RegisterService(&_Member_serviceDesc, srv)
}

func _Member_UpdateSessionKeyByUnionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionKeyByUnionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).UpdateSessionKeyByUnionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/member.member/UpdateSessionKeyByUnionId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).UpdateSessionKeyByUnionId(ctx, req.(*UpdateSessionKeyByUnionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_VerifyUserNumberWithPwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserNumberWithPwdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).VerifyUserNumberWithPwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/member.member/VerifyUserNumberWithPwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).VerifyUserNumberWithPwd(ctx, req.(*VerifyUserNumberWithPwdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Member_serviceDesc = grpc.ServiceDesc{
	ServiceName: "member.member",
	HandlerType: (*MemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "updateSessionKeyByUnionId",
			Handler:    _Member_UpdateSessionKeyByUnionId_Handler,
		},
		{
			MethodName: "verifyUserNumberWithPwd",
			Handler:    _Member_VerifyUserNumberWithPwd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member_data.proto",
}
