// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member_data.proto

package member

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateSessionKeyByUnionIdRequest struct {
	UnionId              string   `protobuf:"bytes,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSessionKeyByUnionIdRequest) Reset()         { *m = UpdateSessionKeyByUnionIdRequest{} }
func (m *UpdateSessionKeyByUnionIdRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSessionKeyByUnionIdRequest) ProtoMessage()    {}
func (*UpdateSessionKeyByUnionIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4010a41aeb367e84, []int{0}
}

func (m *UpdateSessionKeyByUnionIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Unmarshal(m, b)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Merge(m, src)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.Size(m)
}
func (m *UpdateSessionKeyByUnionIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSessionKeyByUnionIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSessionKeyByUnionIdRequest proto.InternalMessageInfo

func (m *UpdateSessionKeyByUnionIdRequest) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *UpdateSessionKeyByUnionIdRequest) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

type UpdateSessionKeyByUnionIdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSessionKeyByUnionIdResponse) Reset()         { *m = UpdateSessionKeyByUnionIdResponse{} }
func (m *UpdateSessionKeyByUnionIdResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSessionKeyByUnionIdResponse) ProtoMessage()    {}
func (*UpdateSessionKeyByUnionIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4010a41aeb367e84, []int{1}
}

func (m *UpdateSessionKeyByUnionIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Unmarshal(m, b)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Merge(m, src)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.Size(m)
}
func (m *UpdateSessionKeyByUnionIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSessionKeyByUnionIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSessionKeyByUnionIdResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpdateSessionKeyByUnionIdRequest)(nil), "member.updateSessionKeyByUnionIdRequest")
	proto.RegisterType((*UpdateSessionKeyByUnionIdResponse)(nil), "member.updateSessionKeyByUnionIdResponse")
}

func init() { proto.RegisterFile("member_data.proto", fileDescriptor_4010a41aeb367e84) }

var fileDescriptor_4010a41aeb367e84 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0xcd, 0x4d,
	0x4a, 0x2d, 0x8a, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83,
	0x08, 0x29, 0xc5, 0x70, 0x29, 0x94, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0x06, 0xa7, 0x16, 0x17, 0x67,
	0xe6, 0xe7, 0x79, 0xa7, 0x56, 0x3a, 0x55, 0x86, 0xe6, 0x65, 0xe6, 0xe7, 0x79, 0xa6, 0x04, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0x97, 0x42, 0x44, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x39, 0x2e, 0xae, 0x62, 0xb8, 0x3e, 0x09, 0x26, 0xb0, 0x24,
	0x92, 0x88, 0x92, 0x32, 0x97, 0x22, 0x1e, 0xd3, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x8d, 0xaa,
	0xb8, 0xa0, 0x8e, 0x11, 0x2a, 0xe0, 0x92, 0xc4, 0xa9, 0x5c, 0x48, 0x43, 0x0f, 0xa2, 0x4a, 0x8f,
	0x90, 0x7b, 0xa5, 0x34, 0x89, 0x50, 0x09, 0xb1, 0x3b, 0x89, 0x0d, 0x1c, 0x1a, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb5, 0xef, 0xb7, 0xee, 0x22, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberClient is the client API for Member service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberClient interface {
	UpdateSessionKeyByUnionId(ctx context.Context, in *UpdateSessionKeyByUnionIdRequest, opts ...grpc.CallOption) (*UpdateSessionKeyByUnionIdResponse, error)
}

type memberClient struct {
	cc *grpc.ClientConn
}

func NewMemberClient(cc *grpc.ClientConn) MemberClient {
	return &memberClient{cc}
}

func (c *memberClient) UpdateSessionKeyByUnionId(ctx context.Context, in *UpdateSessionKeyByUnionIdRequest, opts ...grpc.CallOption) (*UpdateSessionKeyByUnionIdResponse, error) {
	out := new(UpdateSessionKeyByUnionIdResponse)
	err := c.cc.Invoke(ctx, "/member.member/updateSessionKeyByUnionId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServer is the server API for Member service.
type MemberServer interface {
	UpdateSessionKeyByUnionId(context.Context, *UpdateSessionKeyByUnionIdRequest) (*UpdateSessionKeyByUnionIdResponse, error)
}

// UnimplementedMemberServer can be embedded to have forward compatible implementations.
type UnimplementedMemberServer struct {
}

func (*UnimplementedMemberServer) UpdateSessionKeyByUnionId(ctx context.Context, req *UpdateSessionKeyByUnionIdRequest) (*UpdateSessionKeyByUnionIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSessionKeyByUnionId not implemented")
}

func RegisterMemberServer(s *grpc.Server, srv MemberServer) {
	s.RegisterService(&_Member_serviceDesc, srv)
}

func _Member_UpdateSessionKeyByUnionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionKeyByUnionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).UpdateSessionKeyByUnionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/member.member/UpdateSessionKeyByUnionId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).UpdateSessionKeyByUnionId(ctx, req.(*UpdateSessionKeyByUnionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Member_serviceDesc = grpc.ServiceDesc{
	ServiceName: "member.member",
	HandlerType: (*MemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "updateSessionKeyByUnionId",
			Handler:    _Member_UpdateSessionKeyByUnionId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member_data.proto",
}
